version: '3'
services:
    gant:
        build: ./../gant/GantBackend
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - '8000:8000'
        env_file: ./../gant/.env
        networks:
            - sail
        depends_on:
            - mysql
        restart: always
        
    front-gant:
        build:
            context: ./../gant/GantFrontend
            args:
                REACT_APP_API_URL: http://158.160.96.200:88
        ports:
            - "88:80"
        networks:
            - sail
        depends_on:
            - gant
        restart: always
            
    ocenka:
        build: ./../ocenka/Uralintern_2022
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - '5000:8000'
        env_file:
            - ./../ocenka/.env.dev
        networks:
            - sail
        depends_on:
            - mysql
        restart: always

    laravel.test:
        build:
            context: ./docker/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '3000:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
        restart: always
            
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_KABAN_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_KABAN_DATABASE}'
            MYSQL_USER: '${DB_KABAN_USERNAME}'
            MYSQL_PASSWORD: '${DB_KABAN_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
            - './test.sql:/docker-entrypoint-initdb.d/test.sql'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_KABAN_PASSWORD}'
            retries: 3
            timeout: 5s
        restart: always
         
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
